---
title: "About this site"
description: |
  This research study is created by the project team for the fulfilment for SMT201 Geographic Information Systems for Urban Planning.
  
  Instructor: Dr. Kam Tin Seong
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 1. Welcome!

Welcome to our personal page.

# 1.1 Project Github

Please see https://github.com/brown-chicken1/website for our Project GitHub.

# 2. Profiles

# 2.1 Ang Heng Di

Heng di is a second-year undergraduate pursuing a Bachelor of Science in (BSc(IS)), Major in Smart City Management and Technology. Being passionate in utilizing Data to improve the lives of people and places, he joined SMU Business Intelligence and Analytics as a Data Associate and took up various data analytic courses such as Google Data Analytics Specialization and Smartcademy Data Analytic courses. In his free time, he nuture and groom future leaders of Singapore through tutoring and mentoring at Intellect Learning Hub and Chinese Development Assistance Council (CDAC). 

Linkedin: https://www.linkedin.com/in/anghengdi/

# 2.2 Arick Soo

Arick is a second-year undergraduate pursuing a Bachelor of Science in (BSc(IS)), Major in Smart City Management and Technology. As a budding Technologist, he took part in the ASEAN Geo-spatial Challenge recently as he is inspired at how map is driving the next generation mobility experience across all transport types. With Data is at the core on how we make maps smarter, he found ways to utilizes machine learning to solve complex challenges across various transport types allowing his team to emerges as Singapore Finalists and attaining the ASEAN Excellence award. In his free time, he assist with Geo-spatial companies by being a licensed Unmanned Aircraft Pilot to aid in various projects in collaboration with the local town councils.

LinkedIn: https://www.linkedin.com/in/aricksoo/

# 2.3 Sun Hanchen

Hanchen is a third-year undergraduate pursuing a Bachelor of Science (BSc(Econs)), with a second major in Data Science & Analytics. He is a recipient of the SMU Global Impact Scholarship and topped the Economics freshman cohort for AY2019/2020. Passionate about learning about new cultures, exploring new places and improving sustainability practices, Hanchen made the unusual choice to take this course as part of a possible idea to take a second degree in Smart City Management and Technology. He has interned at a fixed asset fund management firm from January to August 2021, and will do internships in policy and risk consulting, as well as decarbonisation strategy, in 2022. Hanchen aims to have a career as a consultant or data analyst in a consulting firm that makes data-driven decisions in the pursuit of net zero emissions or ESG compliance. Asides from his academics, he is the Vice President of SMU Emerging Markets, a finance and research club, and a student consultant at Thrive, a social consulting association serving non-profits.

LinkedIn: https://www.linkedin.com/in/sun-han-chen-4b0482140/