---
title: "Overview of Project"
description: |
  This website comprises an overview of how we wish to tackle the issue of site selection and analysis of a suitable site for the new Jakarta capital city.
  
  A more comprehensive analysis, with citations, is available in our full report
site: distill::distill_website
---
This project serves to recommend a suitable site for the construction of a new capital city in Indonesia. Jakarta, Indonesia’s capital, has long been sinking, sometimes by as much as 10cm a year. A key reason has been the issue with the terrain in Jakarta and human intervention – the poor water network in Indonesia, and especially Jakarta, combined with the huge population, means that a large number of people have to turn to obtaining their own water sources in order to survive. This has resulted in them extracting groundwater, leading to the terrain above it sinking. [1] Some have reasoned that the discriminatory systems of the past when Jakarta was a Dutch colony led to the unequal distribution of infrastructure, a problem that has persisted to this day. [2] It is expected that Jakarta would eventually sink below sea level, a major concern given its status as a capital city, but even more so for the citizens living there, exacerbated by the concerns for climate change.
  
  Our project aims to provide a comprehensive and resilient method to select suitable capital city sites, away from climate change or human activity accelerated natural disasters, but at the same time, economically feasible through relying as much as possible on existing infrastructure. We have done a site survey of our study area in East Kalimantan (Kalimantan Timur) which straddles the land between the existing 2 major cities, Balikpapan and Samarinda. Following that, we used multi-criteria decision analysis to narrow down a specific spot within the city. 

We will provide both choropleth and categorical maps during the survey of the land use, on existing infrastructure, natural and artificial barriers or places of interest of development in Kalimantan. Subsequently, we will explain our reasoning for the decision criteria that we use to weigh different factors over one another, through our underlying principal of first risk mitigation, environmental accountability and fiscal feasibility. We recognise that there are systemic factors on both municipal and national level in Indonesia, and remind ourselves of the rationale for doing so: to build a more climate-resilient and liveable capital city.  
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```
